name: CICD

on:
  push:
    branches: [main]


jobs:
  update-and-run:
    runs-on: self-hosted  # Replace with your AWS EC2 runner configuration
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check if file exists
        run: |
          FILE_PATH="~/edulink-backend"  # Specify the path to the file
          if [ -f "$FILE_PATH" ]; then
            echo "File exists"
            # Perform actions to update the file
            # Example: Use commands to update the file content
          else
            echo "File does not exist"
            # Clone the repository if the file doesn't exist
            git clone https://github.com/Basimohd/edulink-backend.git temp-folder
            cd temp-folder
            # Run the docker-compose command
            docker-compose up -d
          fi

      - name: Cleanup temp folder (if cloned)
        if: ${{ !success() }}  # Clean up only if the file was not found and repository was cloned
        run: |
          rm -rf temp-folder  # Remove the cloned repository if created